# Generated by Django 5.2.4 on 2026-05-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("fields_schema", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Formulario de inscricao",
                "verbose_name_plural": "Formularios de inscricao",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignupSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="core.signupform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscricao enviada",
                "verbose_name_plural": "Inscricoes enviadas",
                "ordering": ["-created_at"],
            },
        ),
    ]
