# Generated by Django 5.2.4 on 2026-07-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_id_cadastro_to_default_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_home_heading',
            field=models.CharField(default='Sobre nos', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_home_highlight',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_home_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_home_paragraph_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_home_paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_home_summary_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge',
            field=models.CharField(default='Portal institucional', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_label',
            field=models.CharField(default='Conheca mais', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_panel_item_1',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_panel_item_2',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_panel_item_3',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_panel_title',
            field=models.CharField(default='Pronto para comecar?', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_button_label',
            field=models.CharField(default='Ver todas', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_eyebrow',
            field=models.CharField(default='Noticias', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_title',
            field=models.CharField(default='Ultimas noticias', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signup_address_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signup_address_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signup_button_label',
            field=models.CharField(default='Inscreva-se', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signup_info_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signup_info_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
