# Generated by Django 5.2.4 on 2026-07-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_message_and_email_destination'),
        ('core', '0005_sitesettings_about_home_heading_and_more'),
    ]

    operations = [
    ]
