from django.urls import path

from .views import (
    AboutView,
    AdminBannerCreateView,
    AdminNewsCreateView,
    AdminPanelView,
    AdminSignupFormCreateView,
    ContactView,
    EventCalendarView,
    EventDetailView,
    EventListView,
    HomeView,
    LinksView,
    MediaView,
    NewsDetailView,
    NewsListView,
    PortalView,
    InitialAdminSetupView,
    SignupView,
    SignupFormDetailView,
    UserLoginView,
    UserLogoutView,
    UserPasswordResetCompleteView,
    UserPasswordResetConfirmView,
    UserPasswordResetDoneView,
    UserPasswordResetView,
    UserRegisterView,
    FileUploadView,
    SearchView,
    set_language,
)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("sobre/", AboutView.as_view(), name="about"),
    path("noticias/", NewsListView.as_view(), name="news-list"),
    path("noticias/<slug:slug>/", NewsDetailView.as_view(), name="news-detail"),
    path("eventos/", EventListView.as_view(), name="event-list"),
    path("eventos/calendario/", EventCalendarView.as_view(), name="event-calendar"),
    path("eventos/<slug:slug>/", EventDetailView.as_view(), name="event-detail"),
    path("midia/", MediaView.as_view(), name="media"),
    path("contato/", ContactView.as_view(), name="contact"),
    path("inscreva-se/", SignupView.as_view(), name="signup"),
    path("inscreva-se/<slug:slug>/", SignupFormDetailView.as_view(), name="signup-form-detail"),
    path("links/", LinksView.as_view(), name="links"),
    path("busca/", SearchView.as_view(), name="search"),
    path("arquivos/", FileUploadView.as_view(), name="file-upload"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("configurar-admin/", InitialAdminSetupView.as_view(), name="initial-admin-setup"),
    path("senha/recuperar/", UserPasswordResetView.as_view(), name="password-reset"),
    path("senha/recuperar/enviado/", UserPasswordResetDoneView.as_view(), name="password-reset-done"),
    path("senha/redefinir/<uidb64>/<token>/", UserPasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("senha/redefinir/concluido/", UserPasswordResetCompleteView.as_view(), name="password-reset-complete"),
    path("sair/", UserLogoutView.as_view(), name="logout"),
    path("cadastro/", UserRegisterView.as_view(), name="register"),
    path("portal/", PortalView.as_view(), name="portal"),
    path("painel-admin/", AdminPanelView.as_view(), name="admin-panel"),
    path("painel-admin/noticias/nova/", AdminNewsCreateView.as_view(), name="admin-news-create"),
    path("painel-admin/carrossel/novo/", AdminBannerCreateView.as_view(), name="admin-banner-create"),
    path("painel-admin/formularios/novo/", AdminSignupFormCreateView.as_view(), name="admin-signup-form-create"),
    path("idioma/", set_language, name="set-language"),
]
