from django.urls import path

from .views import (
    AboutView,
    AdminBannerCreateView,
    AdminBannerListView,
    AdminDashboardView,
    AdminNewsCreateView,
    AdminNewsListView,
    AdminPanelView,
    AdminSignupFormCreateView,
    AdminSignupFormListView,
    AdminSignupSubmissionListView,
    ContactView,
    EventCalendarView,
    EventDetailView,
    EventListView,
    HomeView,
    LinksView,
    MediaView,
    NewsDetailView,
    NewsListView,
    PortalView,
    SignupView,
    SignupFormDetailView,
    UserLoginView,
    UserLogoutView,
    UserRegisterView,
    set_language,
)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("sobre/", AboutView.as_view(), name="about"),
    path("noticias/", NewsListView.as_view(), name="news-list"),
    path("noticias/<slug:slug>/", NewsDetailView.as_view(), name="news-detail"),
    path("eventos/", EventListView.as_view(), name="event-list"),
    path("eventos/calendario/", EventCalendarView.as_view(), name="event-calendar"),
    path("eventos/<slug:slug>/", EventDetailView.as_view(), name="event-detail"),
    path("midia/", MediaView.as_view(), name="media"),
    path("contato/", ContactView.as_view(), name="contact"),
    path("inscreva-se/", SignupView.as_view(), name="signup"),
    path("inscreva-se/<slug:slug>/", SignupFormDetailView.as_view(), name="signup-form-detail"),
    path("links/", LinksView.as_view(), name="links"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("sair/", UserLogoutView.as_view(), name="logout"),
    path("logout/", UserLogoutView.as_view(), name="logout-en"),
    path("cadastro/", UserRegisterView.as_view(), name="register"),
    path("portal/", PortalView.as_view(), name="portal"),
    path("painel-admin/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("painel-admin/conteudo/", AdminPanelView.as_view(), name="admin-panel"),
    path("painel-admin/noticias/", AdminNewsListView.as_view(), name="admin-news-list"),
    path("painel-admin/noticias/nova/", AdminNewsCreateView.as_view(), name="admin-news-create"),
    path("painel-admin/carrossel/", AdminBannerListView.as_view(), name="admin-banner-list"),
    path("painel-admin/carrossel/novo/", AdminBannerCreateView.as_view(), name="admin-banner-create"),
    path("painel-admin/formularios/", AdminSignupFormListView.as_view(), name="admin-signup-form-list"),
    path("painel-admin/formularios/novo/", AdminSignupFormCreateView.as_view(), name="admin-signup-form-create"),
    path("painel-admin/inscricoes/", AdminSignupSubmissionListView.as_view(), name="admin-signup-submission-list"),
    path("idioma/", set_language, name="set-language"),
]
